workflows:
  control-panel-android:
    name: Control Panel Android Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      groups:
        - google_play
      vars:
        PACKAGE_NAME: "com.controlpanel.control_panel_flutter_app"
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Flutter analyze
        script: |
          flutter analyze
      - name: Flutter test
        script: |
          flutter test
      - name: Build APK with Flutter
        script: |
          flutter build apk --release
      - name: Echo APK path
        script: |
          find build/app/outputs/flutter-apk -name "*.apk"
      - name: Copy APK to CM_EXPORT_DIR
        script: |
          mkdir -p $CM_EXPORT_DIR
          cp $(find build/app/outputs/flutter-apk -name "*.apk") $CM_EXPORT_DIR
    artifacts:
      - $CM_EXPORT_DIR/*.apk
      - build/app/outputs/bundle/release/*.aab
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - ibrahimalsattouf88@gmail.com
        notify:
          success: true
          failure: true

  control-panel-ios:
    name: Control Panel iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      groups:
        - app_store_credentials
      vars:
        PACKAGE_NAME: "com.controlpanel.control_panel_flutter_app"
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Flutter analyze
        script: |
          flutter analyze
      - name: Flutter test
        script: |
          flutter test
      - name: Build ipa for distribution
        script: |
          flutter build ipa --release --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - ibrahimalsattouf88@gmail.com
        notify:
          success: true
          failure: true

